#include "native_worker_codegen.h"

#include <string.h>

#include "native_worker_source.h"

static int emit_between(FILE *file, const unsigned char *raw,
                        const char *begin, const char *end) {
    const char *source = (const char *)raw;
    const char *start = strstr(source, begin);
    const char *finish;
    size_t length;
    if (start == NULL) return -1;
    finish = end == NULL ? source + strlen(source) : strstr(start, end);
    if (finish == NULL) return -1;
    length = (size_t)(finish - start);
    return fwrite(start, 1u, length, file) == length ? 0 : -1;
}

int wrtc_native_worker_emit_runtime(FILE *file) {
    if (file == NULL ||
        fputs("#define WRTC_NATIVE_WORKER_EMBEDDED 1\n"
              "#include <limits.h>\n#include <pthread.h>\n"
              "#include <sched.h>\n#include <stdatomic.h>\n"
              "#include <stdlib.h>\n#include <string.h>\n", file) < 0 ||
        emit_between(file, native_worker_abi_h_source, "typedef enum {",
                     "#endif") < 0 ||
        fputs("typedef struct WrtcNativeWorkerExecutor "
              "WrtcNativeWorkerExecutor;\n", file) < 0 ||
        emit_between(file, native_worker_executor_h_source,
                     "typedef enum {", "#endif") < 0 ||
        fputs("int wrtc_native_worker_record_pack(PyObject*,PyTypeObject*,"
              "const WrtcNativeWorkerAbi*,WrtcNativeWorkerRecord*);"
              "PyObject*wrtc_native_worker_record_materialize("
              "const WrtcNativeWorkerRecord*,PyTypeObject*);"
              "void wrtc_native_worker_record_move(WrtcNativeWorkerRecord*,"
              "WrtcNativeWorkerRecord*);"
              "void wrtc_native_worker_record_release("
              "WrtcNativeWorkerRecord*);\n", file) < 0 ||
        emit_between(file, native_worker_record_c_source,
                     "static int unsigned_fits", NULL) < 0 ||
        emit_between(file, native_worker_executor_c_source,
                     "typedef enum {", NULL) < 0)
        return -1;
    return 0;
}

int wrtc_native_worker_emit_cpython_adapter(FILE *file) {
    if (file == NULL) return -1;
    return fputs(
        "#include <errno.h>\n#include <fcntl.h>\n#include <sys/socket.h>\n"
        "#include <unistd.h>\n"
        "typedef struct WA{PyObject_HEAD WrtcNativeWorkerExecutor*x;"
        "PyTypeObject*it;PyTypeObject*ot;const WrtcNativeWorkerAbi*ia;"
        "const WrtcNativeWorkerAbi*oa;PyObject*backlog;PyObject*pending;PyObject*loop;"
        "PyObject*callback;PyObject*owner;const char*callback_name;void*iq;void*oq;int wake_read;int wake_write;"
        "size_t capacity;"
        "unsigned started:1;unsigned closed:1;unsigned closing:1;"
        "unsigned admission_closed:1;unsigned joined:1;"
        "unsigned registered:1;}WA;static void wadt(void*,WA*);"
        "static void wan(void*c){WA*a=(WA*)c;char b=0;if(a&&a->wake_write>=0)"
        "(void)send(a->wake_write,&b,1,MSG_DONTWAIT);}"
        "static int wacap(const WrtcNativeWorkerRecord*r,"
        "const WrtcNativeWorkerError*e,void*c){WA*a=(WA*)c;PyObject*v,*q;"
        "if(e&&e->code!=WRTC_WORKER_ERROR_NONE){v=PyObject_CallFunction("
        "PyExc_RuntimeError,\"sik\",\"native packet worker failed\","
        "(int)e->code,(unsigned long long)e->sequence);if(!v)return -1;"
        "q=PyTuple_Pack(2,Py_False,v);Py_DECREF(v);}else{v="
        "wrtc_native_worker_record_materialize(r,a->ot);if(!v)return -1;"
        "q=PyTuple_Pack(2,Py_True,v);Py_DECREF(v);}if(!q)return -1;"
        "if(PyList_Append(a->backlog,q)<0){Py_DECREF(q);return -1;}"
        "Py_DECREF(q);return 0;}"
        "static int wat(WA*a,visitproc visit,void*arg){Py_VISIT(a->it);"
        "Py_VISIT(a->ot);Py_VISIT(a->backlog);Py_VISIT(a->pending);Py_VISIT(a->loop);"
        "Py_VISIT(a->callback);Py_VISIT(a->owner);return 0;}"
        "static void wau(WA*a){PyObject*l,*r;if(!a->registered)return;"
        "a->registered=0u;l=a->loop?Py_NewRef(a->loop):NULL;"
        "if(!l||a->wake_read<0){Py_XDECREF(l);return;}"
        "r=PyObject_CallMethod(l,\"_remove_reader\",\"i\",a->wake_read);"
        "Py_DECREF(l);if(!r)PyErr_Clear();else Py_DECREF(r);}"
        "static int wacl(WA*a){WrtcNativeWorkerExecutor*x;PyObject*et=NULL,*ev=NULL,*tb=NULL;int rd,wr;"
        "if(a->closed||a->closing)return 0;a->closing=1u;"
        "PyErr_Fetch(&et,&ev,&tb);wau(a);"
        "wadt(a->iq,a);wadt(a->oq,a);a->iq=NULL;a->oq=NULL;"
        "x=a->x;a->x=NULL;if(x){wrtc_native_worker_executor_close_admission(x);"
        "if(wrtc_native_worker_executor_shutdown(x,wacap,a)<0)PyErr_Clear();"
        "wrtc_native_worker_executor_destroy(x);}"
        "rd=a->wake_read;wr=a->wake_write;a->wake_read=-1;a->wake_write=-1;"
        "if(rd>=0)close(rd);if(wr>=0)close(wr);"
        "a->closed=1u;a->admission_closed=1u;a->joined=1u;"
        "Py_CLEAR(a->it);Py_CLEAR(a->ot);Py_CLEAR(a->backlog);Py_CLEAR(a->pending);"
        "Py_CLEAR(a->loop);Py_CLEAR(a->callback);Py_CLEAR(a->owner);"
        "a->closing=0u;PyErr_Clear();PyErr_Restore(et,ev,tb);return 0;}"
        "static void wad(WA*a){PyObject_GC_UnTrack(a);(void)wacl(a);"
        "Py_TYPE(a)->tp_free((PyObject*)a);}"
        "static PyObject*wast(WA*a,PyObject*u){int z;(void)u;if(a->closed||"
        "!a->x){PyErr_SetString(PyExc_RuntimeError,\"worker is closed\");"
        "return NULL;}if(a->started){PyErr_SetString(PyExc_RuntimeError,"
        "\"threads can only be started once\");return NULL;}z="
        "wrtc_native_worker_executor_start(a->x);if(z<0)return PyErr_SetFromErrno("
        "PyExc_OSError);a->started=1u;while(a->pending&&PyList_GET_SIZE(a->pending)>0){"
        "WrtcNativeWorkerRecord q={0};WrtcNativeWorkerTicket t;"
        "PyObject*v=PyList_GET_ITEM(a->pending,0);WrtcNativeWorkerExecutorStatus s;"
        "if(wrtc_native_worker_record_pack(v,a->it,a->ia,&q)<0)return NULL;"
        "s=wrtc_native_worker_executor_try_submit(a->x,&q,&t);"
        "if(s!=WRTC_WORKER_EXECUTOR_OK){wrtc_native_worker_record_release(&q);"
        "PyErr_SetString(PyExc_RuntimeError,\"pre-start worker queue flush failed\");return NULL;}"
        "if(PySequence_DelItem(a->pending,0)<0)return NULL;}"
        "if(a->admission_closed)wrtc_native_worker_executor_close_admission(a->x);"
        "Py_RETURN_NONE;}"
        "static PyObject*waco(WA*a,PyObject*u){(void)u;if(a->x&&a->started)"
        "wrtc_native_worker_executor_close_admission(a->x);"
        "a->admission_closed=1u;if(a->started||!a->pending||"
        "PyList_GET_SIZE(a->pending)==0)wau(a);Py_RETURN_NONE;}"
        "static PyObject*wajo(WA*a,PyObject*args,PyObject*kwargs){"
        "static char*kw[]={\"timeout\",NULL};PyObject*t=Py_None;"
        "if(!PyArg_ParseTupleAndKeywords(args,kwargs,\"|O:join\",kw,&t))"
        "return NULL;if(t!=Py_None){PyErr_SetString(PyExc_NotImplementedError,"
        "\"native worker join timeout is unsupported\");return NULL;}"
        "if(!a->started){PyErr_SetString(PyExc_RuntimeError,"
        "\"cannot join thread before it is started\");return NULL;}"
        "if(a->x&&!a->joined){if(wrtc_native_worker_executor_shutdown("
        "a->x,wacap,a)<0)return NULL;a->joined=1u;}Py_RETURN_NONE;}"
        "static PyObject*waal(WA*a,PyObject*u){(void)u;return PyBool_FromLong("
        "a->x&&a->started&&!wrtc_native_worker_executor_is_stopped(a->x));}"
        "static PyObject*wadr(WA*a,PyObject*u){char b[64];PyObject*q,*v,*r;"
        "PyObject*et=NULL,*ev=NULL,*tb=NULL;"
        "(void)u;while(a->wake_read>=0&&recv(a->wake_read,b,sizeof b,"
        "MSG_DONTWAIT)>0){}while(a->x&&wrtc_native_worker_executor_"
        "try_consume(a->x,wacap,a)==WRTC_WORKER_EXECUTOR_OK){}"
        "if(a->x)(void)wrtc_native_worker_executor_consumer_rearm(a->x);"
        "while(a->backlog&&PyList_GET_SIZE(a->backlog)>0){q=Py_NewRef("
        "PyList_GET_ITEM(a->backlog,0));if(PySequence_DelItem(a->backlog,0)<0)"
        "{Py_DECREF(q);return NULL;}v=PyTuple_GET_ITEM(q,1);"
        "if(PyTuple_GET_ITEM(q,0)==Py_False){PyErr_SetObject((PyObject*)"
        "Py_TYPE(v),v);Py_DECREF(q);if(!et)PyErr_Fetch(&et,&ev,&tb);"
        "else PyErr_Clear();continue;}if(a->owner&&a->callback_name){"
        "PyObject*cb=PyObject_GetAttrString(a->owner,a->callback_name);if(!cb){Py_DECREF(q);return NULL;}"
        "r=PyObject_CallOneArg(cb,v);Py_DECREF(cb);}else r=PyObject_CallOneArg(a->callback,v);"
        "Py_DECREF(q);if(!r){if(!et)PyErr_Fetch(&et,&ev,&tb);else PyErr_Clear();"
        "continue;}Py_DECREF(r);}if(et){PyErr_Restore(et,ev,tb);return NULL;}"
        "Py_RETURN_NONE;}"
        "static PyMethodDef wam[]={{\"start\",(PyCFunction)wast,METH_NOARGS,NULL},"
        "{\"close\",(PyCFunction)waco,METH_NOARGS,NULL},"
        "{\"join\",(PyCFunction)(void(*)(void))wajo,METH_VARARGS|METH_KEYWORDS,NULL},"
        "{\"is_alive\",(PyCFunction)waal,METH_NOARGS,NULL},"
        "{\"drain\",(PyCFunction)wadr,METH_NOARGS,NULL},"
        "{NULL,NULL,0,NULL}};"
        "static PyType_Slot was[]={ {Py_tp_dealloc,(void*)wad},"
        "{Py_tp_traverse,(void*)wat},{Py_tp_clear,(void*)wacl},"
        "{Py_tp_methods,(void*)wam},{0,NULL}};"
        "static PyType_Spec wasp={\"pymeta.NativeWorkerThreadAdapter\","
        "sizeof(WA),0,Py_TPFLAGS_DEFAULT|Py_TPFLAGS_HAVE_GC,was};"
        "static WA*wane(PyTypeObject*t,size_t cap,const WrtcNativeWorkerAbi*ia,"
        "const WrtcNativeWorkerAbi*oa,PyTypeObject*it,PyTypeObject*ot,"
        "WrtcNativeWorkerKernel k,PyObject*loop,PyObject*callback,PyObject*owner,const char*callback_name,"
        "void*iq,void*oq){int sv[2];"
        "PyObject*bound=NULL,*r=NULL;WA*a;if(socketpair(AF_UNIX,SOCK_STREAM,0,sv)<0)"
        "return (WA*)PyErr_SetFromErrno(PyExc_OSError);a=PyObject_GC_New(WA,t);"
        "if(!a){close(sv[0]);close(sv[1]);return NULL;}a->x=NULL;"
        "a->it=(PyTypeObject*)Py_NewRef((PyObject*)it);"
        "a->ot=(PyTypeObject*)Py_NewRef((PyObject*)ot);a->ia=ia;a->oa=oa;"
        "a->backlog=PyList_New(0);a->pending=PyList_New(0);a->loop=Py_NewRef(loop);"
        "a->callback=Py_NewRef(callback);a->owner=Py_NewRef(owner);a->callback_name=callback_name;a->iq=iq;a->oq=oq;"
        "a->wake_read=sv[0];a->wake_write=sv[1];a->capacity=cap;"
        "a->started=0u;a->closed=0u;a->closing=0u;a->admission_closed=0u;"
        "a->joined=0u;a->registered=0u;"
        "PyObject_GC_Track(a);"
        "(void)fcntl(sv[0],F_SETFL,fcntl(sv[0],F_GETFL,0)|O_NONBLOCK);"
        "(void)fcntl(sv[1],F_SETFL,fcntl(sv[1],F_GETFL,0)|O_NONBLOCK);"
        "if(!a->backlog||!a->pending||"
        "wrtc_native_worker_executor_create(&a->x,cap,cap,ia,oa,k,NULL,wan,a)<0)"
        "{Py_DECREF(a);if(!PyErr_Occurred())PyErr_NoMemory();return NULL;}"
        "bound=PyObject_GetAttrString((PyObject*)a,\"drain\");if(!bound)"
        "{Py_DECREF(a);return NULL;}r=PyObject_CallMethod(loop,\"_add_reader\","
        "\"iO\",sv[0],bound);Py_DECREF(bound);if(!r){Py_DECREF(a);return NULL;}"
        "Py_DECREF(r);a->registered=1u;return a;}"
        "static PyObject*wasub(WA*a,PyObject*v){WrtcNativeWorkerRecord r={0};"
        "WrtcNativeWorkerTicket t;WrtcNativeWorkerExecutorStatus z;if(!a||!a->x)"
        "return PyErr_Format(PyExc_RuntimeError,\"worker is closed\");"
        "if(wrtc_native_worker_record_pack(v,a->it,a->ia,&r)<0)return NULL;"
        "if(!a->started){wrtc_native_worker_record_release(&r);"
        "if(a->admission_closed){PyErr_SetString(PyExc_RuntimeError,"
        "\"worker queue is closed\");return NULL;}"
        "if((size_t)PyList_GET_SIZE(a->pending)>=a->capacity){PyErr_SetString("
        "PyExc_RuntimeError,\"native worker input queue is full\");return NULL;}"
        "if(PyList_Append(a->pending,v)<0)return NULL;Py_RETURN_NONE;}"
        "z=wrtc_native_worker_executor_try_submit(a->x,&r,&t);"
        "if(z!=WRTC_WORKER_EXECUTOR_OK)wrtc_native_worker_record_release(&r);"
        "if(z==WRTC_WORKER_EXECUTOR_OK)Py_RETURN_NONE;"
        "if(z==WRTC_WORKER_EXECUTOR_FULL){PyErr_SetString(PyExc_RuntimeError,"
        "\"native worker input queue is full\");return NULL;}"
        "return PyErr_Format(PyExc_RuntimeError,\"worker queue is closed\");}"
        "static PyObject*wapop(WA*a){PyObject*v;if(!a||!a->pending||"
        "PyList_GET_SIZE(a->pending)==0)return NULL;v=Py_NewRef("
        "PyList_GET_ITEM(a->pending,0));if(PySequence_DelItem(a->pending,0)<0){"
        "Py_DECREF(v);return NULL;}if(a->admission_closed&&!a->started&&"
        "PyList_GET_SIZE(a->pending)==0)wau(a);return v;}"
        "static Py_ssize_t waqs(WA*a){size_t n=a&&a->x?"
        "wrtc_native_worker_executor_completion_count(a->x):0u;"
        "if(a&&a->backlog)n+=(size_t)PyList_GET_SIZE(a->backlog);"
        "return n>(size_t)PY_SSIZE_T_MAX?PY_SSIZE_T_MAX:(Py_ssize_t)n;}"
        "static PyObject*wag(WA*a){PyObject*q,*v;if(!a||!a->backlog)"
        "return PyErr_Format(PyExc_RuntimeError,\"worker is closed\");"
        "if(PyList_GET_SIZE(a->backlog)==0&&a->x){WrtcNativeWorkerExecutorStatus z="
        "wrtc_native_worker_executor_try_consume(a->x,wacap,a);"
        "if(z==WRTC_WORKER_EXECUTOR_EMPTY)return NULL;if(z!=WRTC_WORKER_EXECUTOR_OK)"
        "return PyErr_Format(PyExc_RuntimeError,\"worker completion is closed\");}"
        "if(PyList_GET_SIZE(a->backlog)==0)return NULL;q=Py_NewRef("
        "PyList_GET_ITEM(a->backlog,0));if(PySequence_DelItem(a->backlog,0)<0)"
        "{Py_DECREF(q);return NULL;}v=Py_NewRef(PyTuple_GET_ITEM(q,1));"
        "if(PyTuple_GET_ITEM(q,0)==Py_False)PyErr_SetObject((PyObject*)Py_TYPE(v),v);"
        "Py_DECREF(q);if(PyErr_Occurred()){Py_DECREF(v);return NULL;}return v;}\n",
        file) < 0 ? -1 : 0;
}
