[tool.poetry]
name = "webrtc"
version = "0.1.0"
description = ""
authors = ["romashorodok <108732029+romashorodok@users.noreply.github.com>"]
readme = "README.md"
packages = [
  {include = "webrtc", from = "src"},
  {include = "tests", from = "src"},
  {include = "native", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.13"
psutil = "^6.0.0"
cryptography = "44.0.0"
pyopenssl = "^24.1.0"
pylibsrtp = "^0.10.0"
asn1crypto = "^1.5.1"
starkbank-ecdsa = "^2.2.0"
pycryptodome = "^3.21.0"
ecdsa = "^0.19.0"
pytest = "^8.3.4"
maturin = "^1.8.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.3"

[tool.maturin]
python-source = "src"
features = ["pyo3/extension-module"]
module-name = "native.native"

# [build-system]
# requires = ["maturin>=1.8,<2.0"]
# build-backend = "maturin"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
