class DTLS:
    def __init__(self, client: bool, threads: int = 4) -> None: ...
    def do_handshake(self) -> None: ...
    def enqueue_record(self, record: bytes) -> None: ...
    async def dequeue_record(self): ...
