[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
p256 = { version = "0.13", features = ["default", "ecdh", "ecdsa"] }
thiserror = "2"
rand_core = "0.6"
rand = "0.8"
sec1 = { version = "0.7", features = [ "std" ] }
aes-gcm = "0.10"
sha1 = "0.10"
sha2 = "0.10"
hmac = "0.12"
ring = "0.17"
rcgen = "0.13"
rustls = { version = "0.23.10", default-features = false, features = ["std", "ring"] }
byteorder = "1"
