[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
webrtc_dtls = { version = "0.11.0", path = "./dtls", package = "webrtc-dtls" }
